// Aaron Liszt
// TESTS: resetCapacity

#include <iostream>
#include <cassert>
#include "string.hpp"

int main(){
	{
		// SETUP
		String s;

		// TEST
		s.resetCapacity(0);

		// VERIFY
		assert(0 == s.capacity());
	}
	{
		// SETUP
		String s("abc");

		// TEST
		s.resetCapacity(1);

		// VERIFY
		assert(1 == s.capacity());
		assert(s == "");
	}
	{
		// SETUP
		String s("abc");

		// TEST
		s.resetCapacity(2);

		// VERIFY
		assert(2 == s.capacity());
		assert(s == "a");
	}
	{
		// SETUP
		String s;

		// TEST
		s.resetCapacity(300);

		// VERIFY
		assert(300 == s.capacity());
	}
	{
		// SETUP
		String s("a");

		// TEST
		s.resetCapacity(1);

		// VERIFY
		assert(1 == s.capacity());
		assert(s == "");
	}
	{
		// SETUP
		String s("abc");

		// TEST
		s.resetCapacity(300);

		// VERIFY
		assert(300 == s.capacity());
		assert(s == "abc");
	}
	{
		// SETUP
		String s("abc");

		// TEST
		s.resetCapacity(2);

		// VERIFY
		assert(2 == s.capacity());
		assert(s == "a");
	}
	{
		// SETUP
		String s("abc");

		// TEST
		s.resetCapacity(1);

		// VERIFY
		assert(1 == s.capacity());
		assert(s == "");
	}
	{
		// SETUP
		String s("AYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY LMAOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO");

		// TEST
		s.resetCapacity(4);

		// VERIFY
		assert(4 == s.capacity());
		assert(s == "AYY");
	}
	{
		// SETUP
		String s("Gotem");

		// TEST
		s.resetCapacity(256);

		// VERIFY
		assert(256 == s.capacity());
		assert(s == "Gotem");
	}
	{
		// SETUP
		String s("                                                                                                                                                             ");

		// TEST
		s.resetCapacity(5);

		// VERIFY
		assert(5 == s.capacity());
		assert(s == "    ");
	}
	{
		// SETUP
		String s("HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA123456");
		// TEST
		s.resetCapacity(256);

		// VERIFY
		assert(s == "HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA12345");
		assert(256 == s.capacity());
	}
	{
		// SETUP
		String s("HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA12345");

		// TEST
		s.resetCapacity(256);

		// VERIFY
		assert(256 == s.capacity());
		assert(s == "HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA12345");
	}
	{
		// SETUP
		String s("HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA123456789");

		// TEST
		s.resetCapacity(260);

		// VERIFY
		assert(260 == s.capacity());
		assert(s == "HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA123456789");
	}
	{
		// SETUP
		String s("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO");

		// TEST
		s.resetCapacity(0);

		// VERIFY
		assert(0 == s.capacity());
	}
	std::cout << "Done testing resetCapacity." << std::endl;
}

